### PR TITLE
feat: add sample ecs fargate service manifests

### PR DESCRIPTION
**Pull request by CIPHERTron**
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?
This PR adds sample manifests for an ecs fargate type service. These manifests are to be used in the CD Onboarding Guide ([here](https://developer.harness.io/docs/continuous-delivery/cd-onboarding/new-user/onboarding-path#services)) as example services. For that, we needed public manifests that can be directly used by our customers. hence, adding the manifests to this public repo.

- [ ] Issue
- [X] New Application

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@ravilach could you PTAL at this PR and merge it? Thanks!

**Comment by ravilach** [comment]
@CIPHERTron the ARN/Security Group are not real / obfuscated?

**Comment by CIPHERTron** [comment]
Fair point. Let me replace them with dummy values

**Comment by CIPHERTron** [comment]
Done! @ravilach

**Review by ravilach — APPROVED** [review]

**Comment by CIPHERTron** [comment]
Thank you @ravilach 🙏🏻

**Pull request merged**
